$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'common.ps1')

$root = Get-ProjectRoot
$paths = @(
    '.tools',
    '.deployer-cache',
    'artifacts',
    'config',
    'data',
    'logs',
    'reports',
    'deployer',
    'deployer\address',
    'sequencer',
    'batcher',
    'proposer'
)

foreach ($path in $paths) {
    Ensure-Directory (Join-Path $root $path)
}

$envExample = Join-Path $root '.env.example'
$envFile = Join-Path $root '.env'
if ((Test-Path $envExample) -and -not (Test-Path $envFile)) {
    Copy-Item -LiteralPath $envExample -Destination $envFile
}

$batcherGenerated = Join-Path $root 'batcher\.env.generated'
if (-not (Test-Path $batcherGenerated)) {
    Set-Content -LiteralPath $batcherGenerated -Value "# generated by scripts/setup-rollup.ps1`n" -Encoding ASCII
}

$proposerGenerated = Join-Path $root 'proposer\.env.generated'
if (-not (Test-Path $proposerGenerated)) {
    Set-Content -LiteralPath $proposerGenerated -Value "# generated by scripts/setup-rollup.ps1`n" -Encoding ASCII
}

Write-Host "Bootstrap complete: $root"
